Repository vexxhost/atmosphere, pull requests merged in 2024-08, with the labels that each got.

#1732 [ATMOSPHERE-340] Support collect softirq for node-exporter
  roles/kube_prometheus_stack/vars/main.yml
Labels: gate

#1735 [ATMOSPHERE-343] Support collect softirq for node-exporter
  roles/kube_prometheus_stack/vars/main.yml
Labels: gate

#1740 [ATMOSPHERE-336] zed libvirt exporter not having libvirt nova setting enabled
  charts/libvirt/templates/daemonset-libvirt.yaml
Labels: gate

#1737 [ATMOSPHERE-337] 2024 1 caracal libvirt exporter not having libvirt nova setting enabled
  charts/libvirt/templates/daemonset-libvirt.yaml
Labels: gate

#1739 [ATMOSPHERE-339] Support libvirt.nova metadata in metrics for libvirt …
  charts/libvirt/templates/daemonset-libvirt.yaml
Labels: gate

#1738 [ATMOSPHERE-338] Support libvirt.nova metadata in metrics for libvirt …
  charts/libvirt/templates/daemonset-libvirt.yaml
Labels: gate

#1736 [ATMOSPHERE-344] 2024 1 caracal enable softirq monitoring
  roles/kube_prometheus_stack/vars/main.yml
Labels: gate

#1734 [ATMOSPHERE-342] zed enable softirq monitoring
  roles/kube_prometheus_stack/vars/main.yml
Labels: gate

#1752 [ATMOSPHERE-385] chore: sync vendor charts
  .charts.yml
  charts/ironic/Chart.yaml
  charts/ironic/charts/helm-toolkit/Chart.yaml
  charts/ironic/charts/helm-toolkit/templates/endpoints/_authenticated_endpoint_uri_lookup.tpl
  charts/ironic/charts/helm-toolkit/templates/endpoints/_authenticated_transport_endpoint_uri_lookup.tpl
  charts/ironic/charts/helm-toolkit/templates/scripts/_db-drop.py.tpl
  charts/ironic/charts/helm-toolkit/templates/scripts/_db-init.py.tpl
  charts/ironic/charts/helm-toolkit/templates/snippets/_image.tpl
  charts/ironic/charts/helm-toolkit/templates/snippets/_kubernetes_entrypoint_init_container.tpl
  charts/ironic/requirements.lock
  charts/ironic/requirements.yaml
  charts/ironic/templates/bin/_ironic-conductor-http-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-http.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe.sh.tpl
  charts/ironic/templates/configmap-bin.yaml
  charts/ironic/templates/configmap-etc.yaml
  charts/ironic/templates/statefulset-conductor.yaml
  charts/ironic/values.yaml
  charts/libvirt/templates/daemonset-libvirt.yaml
  charts/patches/libvirt/0002-enable-nova-metadata-parser.patch
Labels: gate

#1750 [ATMOSPHERE-379] Add openvswitch image pull for caching before upgrade
  roles/openvswitch/tasks/main.yml
Labels: gate

#1760 [ATMOSPHERE-397] Add CommonName for monitoring stack
  roles/kube_prometheus_stack/defaults/main.yml
  roles/kube_prometheus_stack/vars/main.yml
Labels: gate

#1769 [ATMOSPHERE-388] chore: sync vendor charts
  .charts.yml
  charts/ironic/Chart.yaml
  charts/ironic/templates/bin/_ironic-conductor-http-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-http.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe.sh.tpl
  charts/ironic/templates/configmap-bin.yaml
  charts/ironic/templates/configmap-etc.yaml
  charts/ironic/templates/statefulset-conductor.yaml
  charts/ironic/values.yaml
  charts/libvirt/templates/daemonset-libvirt.yaml
  charts/patches/libvirt/0002-enable-nova-metadata-parser.patch
  charts/placement/templates/bin/_placement-api.sh.tpl
Labels: gate

#1768 [ATMOSPHERE-387] chore: sync vendor charts
  .charts.yml
  charts/ironic/Chart.yaml
  charts/ironic/templates/bin/_ironic-conductor-http-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-http.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe.sh.tpl
  charts/ironic/templates/configmap-bin.yaml
  charts/ironic/templates/configmap-etc.yaml
  charts/ironic/templates/statefulset-conductor.yaml
  charts/ironic/values.yaml
  charts/libvirt/templates/daemonset-libvirt.yaml
  charts/patches/libvirt/0002-enable-nova-metadata-parser.patch
Labels: gate

#1767 [ATMOSPHERE-386] chore: sync vendor charts
  .charts.yml
  charts/ironic/Chart.yaml
  charts/ironic/templates/bin/_ironic-conductor-http-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-http.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe.sh.tpl
  charts/ironic/templates/configmap-bin.yaml
  charts/ironic/templates/configmap-etc.yaml
  charts/ironic/templates/statefulset-conductor.yaml
  charts/ironic/values.yaml
  charts/libvirt/templates/daemonset-libvirt.yaml
  charts/patches/libvirt/0002-enable-nova-metadata-parser.patch
Labels: gate

#1745 [ATMOSPHERE-374] Enable Nova automatic host discovery at a set interval
  roles/nova/vars/main.yml
Labels: gate

#1766 [ATMOSPHERE-389] chore: sync vendor charts
  .charts.yml
  charts/ironic/Chart.yaml
  charts/ironic/templates/bin/_ironic-conductor-http-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-http.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe-init.sh.tpl
  charts/ironic/templates/bin/_ironic-conductor-pxe.sh.tpl
  charts/ironic/templates/configmap-bin.yaml
  charts/ironic/templates/configmap-etc.yaml
  charts/ironic/templates/statefulset-conductor.yaml
  charts/ironic/values.yaml
  charts/libvirt/templates/daemonset-libvirt.yaml
  charts/patches/libvirt/0002-enable-nova-metadata-parser.patch
  charts/placement/templates/bin/_placement-api.sh.tpl
Labels: gate

#1746 [ATMOSPHERE-378] Enable Nova automatic host discovery at a set interval
  roles/nova/vars/main.yml
Labels: gate

#1748 [ATMOSPHERE-377] Enable Nova automatic host discovery at a set interval
  roles/nova/vars/main.yml
Labels: gate

#1749 [ATMOSPHERE-375] Enable Nova automatic host discovery at a set interval
  roles/nova/vars/main.yml
Labels: gate

#1744 Tune database values
  roles/barbican/vars/main.yml
  roles/cinder/vars/main.yml
  roles/designate/vars/main.yml
  roles/glance/vars/main.yml
  roles/heat/vars/main.yml
  roles/keystone/vars/main.yml
  roles/magnum/vars/main.yml
  roles/manila/vars/main.yml
  roles/neutron/vars/main.yml
  roles/nova/vars/main.yml
  roles/octavia/vars/main.yml
  roles/placement/vars/main.yml
  roles/staffeln/vars/main.yml
Labels: gate

#1754 [ATMOSPHERE-382] Add openvswitch image pull for caching before upgrade
  roles/openvswitch/tasks/main.yml
Labels: gate

#1751 [ATMOSPHERE-383] Add openvswitch image pull for caching before upgrade
  roles/openvswitch/tasks/main.yml
Labels: gate

#1775 Add TLS to node exporter
  roles/defaults/vars/main.yml
  roles/kube_prometheus_stack/defaults/main.yml
  roles/kube_prometheus_stack/tasks/main.yml
  roles/kube_prometheus_stack/vars/main.yml
Labels: gate

#1780 [stable/zed] Add TLS to node exporter
  roles/defaults/vars/main.yml
  roles/kube_prometheus_stack/defaults/main.yml
  roles/kube_prometheus_stack/tasks/main.yml
  roles/kube_prometheus_stack/vars/main.yml
Labels: gate

#1781 [stable/2023.1] Add TLS to node exporter
  roles/defaults/vars/main.yml
  roles/kube_prometheus_stack/defaults/main.yml
  roles/kube_prometheus_stack/tasks/main.yml
  roles/kube_prometheus_stack/vars/main.yml
Labels: gate

#1747 [ATMOSPHERE-376] Enable Nova automatic host discovery at a set interval
  roles/nova/vars/main.yml
Labels: gate

#1770 Clean-up quick start docs
  doc/source/quick-start.rst
Labels: gate

#1786 [ATMOSPHERE-322] Fix run multipathd role failure (#1716)
  playbooks/openstack.yml
Labels: gate

#1787 [ATMOSPHERE-323] Fix run multipathd role failure (#1716)
  playbooks/openstack.yml
Labels: gate

#1789 [ATMOSPHERE-325] Fix run multipathd role failure (#1716)
  playbooks/openstack.yml
Labels: gate

#1788 [ATMOSPHERE-324] Fix run multipathd role failure (#1716)
  playbooks/openstack.yml
Labels: gate

#1791 fix: Pass required environment to tox
  roles/manila/defaults/main.yml
  tox.ini
Labels: gate

#1790 [ATMOSPHERE-390] Reduce the ingress controller grace shutdown period
  roles/ingress_nginx/vars/main.yml
Labels: gate

#1796 [PS-292] [stable/2023.1] fix: update neutron policy rules
  roles/neutron/vars/main.yml
Labels: gate

#1806 [CLOUDOPS-344] fix: bump cinder chart and add bootstrap fix
  .charts.yml
  charts/cinder/Chart.yaml
  charts/cinder/templates/bin/_bootstrap.sh.tpl
  charts/cinder/templates/deployment-api.yaml
  charts/cinder/templates/deployment-backup.yaml
  charts/cinder/templates/deployment-scheduler.yaml
  charts/cinder/templates/deployment-volume.yaml
  charts/cinder/templates/secret-db.yaml
  charts/cinder/templates/secret-external-ceph-keyring.yaml
  charts/cinder/templates/secret-keystone.yaml
  charts/cinder/templates/secret-rabbitmq.yaml
  charts/cinder/values.yaml
Labels: gate

#1799 [ATMOSPHERE-392] 2023 1 antelope allow for smoother ingress nginx upgrades
  roles/ingress_nginx/vars/main.yml
Labels: gate

#1793 [PS-292] fix: update new neutron policy rules
  roles/neutron/vars/main.yml
Labels: gate

#1800 [ATMOSPHERE-391] zed allow for smoother ingress nginx upgrades
  roles/ingress_nginx/vars/main.yml
Labels: gate

#1805 [ATMOSPHERE-405] fix: wait until keycloak ready
  roles/keycloak/tasks/main.yml
Labels: gate

#1792 [ATMOSPHERE-403] Rehash certificates to allow Ansible to run
  roles/cluster_issuer/handlers/main.yml
Labels: gate

#1803 [PS-292] fix: image: bump neutron policy server version
  images/neutron/Dockerfile
Labels: gate

#1798 [ATMOSPHERE-394] 2023 2 bobcat allow for smoother ingress nginx upgrades
  roles/ingress_nginx/vars/main.yml
Labels: gate

#1807 [CLOUDOPS-344] [stable/2024.1] fix: bump cinder chart and add bootstra…
  charts/cinder/templates/bin/_bootstrap.sh.tpl
  charts/patches/cinder/0002-fix-fix-volume-type-create-to-honor-encrypt-type.patch
Labels: gate

#1689 [ATMOSPHERE-253] docs: Add how to access the cloud
  doc/source/quick-start.rst
Labels: documentation, gate

#1822 feat: specify api microversion for nova client in magnum conf
  roles/magnum/vars/main.yml
Labels: gate

#1241 [ATMOSPHERE-362] generate_workspace: Set mgr/cephadm/warn_on_stray_daemons to false
  roles/rook_ceph_cluster/tasks/main.yml
Labels: bug, gate

#1821 [CLOUDOPS-348] feat: upgrade mcapi version to 0.22
  images/magnum/Dockerfile
Labels: gate

#1840 [ATMOSPHERE-428] Fix goldpinger grafana dashboard threshold for nodes
  roles/kube_prometheus_stack/files/dashboards/goldpinger.json
Labels: gate

#1841 [ATMOSPHERE-433] Fix ethtool tuning for NICs without rx-{mini,jumbo}
  roles/ethtool/files/ethtool
Labels: gate

#495 [ATMOSPHERE-103] chore: Add loki rule to delect Nova cell down
  roles/loki/vars/main.yml
Labels: gate

#1845 [ATMOSPHERE-432] Fix goldpinger grafana dashboard threshold for nodes…
  roles/kube_prometheus_stack/files/dashboards/goldpinger.json
Labels: gate

#1844 [ATMOSPHERE-429] Fix goldpinger grafana dashboard threshold for nodes…
  roles/kube_prometheus_stack/files/dashboards/goldpinger.json
Labels: gate

#1842 [ATMOSPHERE-431] Fix goldpinger grafana dashboard threshold for nodes…
  roles/kube_prometheus_stack/files/dashboards/goldpinger.json
Labels: gate
