Repository vexxhost/atmosphere, pull requests merged in 2024-05, with the labels that each got.

#1174 ipmi-exporter: Ignore sensor IDs 88/109/111 (Entity Presence)
  roles/ipmi_exporter/defaults/main.yml
Labels: gate

#1181 fix: fix sync-charts CI
  .charts.yml
  charts/neutron/Chart.yaml
  charts/neutron/values.yaml
Labels: gate

#1205 Add evacuate notes
  doc/source/admin/maintenance.rst
Labels: gate

#1204 docs/glance: Fix typo in image_format section name for cinder backend
  doc/source/deploy/glance.rst
Labels: gate

#1177 fix: use kubelet_hostname instead of inventory_hostname_short
  roles/kubernetes_node_labels/tasks/main.yml
Labels: gate

#1190 Add python-ironicclient to Nova image
  images/nova/Dockerfile
Labels: gate

#1217 feat: add Cloudflare ACME solver
  roles/cluster_issuer/defaults/main.yml
  roles/cluster_issuer/tasks/type/acme/solver/cloudflare.yml
Labels: gate

#1208 fix: Horizon custom logo format error with SVG file
  .charts.yml
  charts/horizon/templates/bin/_horizon.sh.tpl
  charts/horizon/values.yaml
  doc/source/config/horizon.rst
  doc/source/config/index.rst
Labels: gate

#1184 fix: Install qemu-block-extra in nova, cinder, ironic images
  images/glance/Dockerfile
  images/ironic/Dockerfile
  images/nova/Dockerfile
Labels: gate

#1225 fix(images): change zed branch name
  images/glance/Dockerfile
  images/horizon/Dockerfile
  images/neutron/Dockerfile
  images/octavia/Dockerfile
Labels: gate

#1210 Ignore ansible-lint warnings about storpool files and zuul.d dir
  .ansible-lint
  galaxy.yml
Labels: ci, gate

#1216 feat: trust private acme CA
  roles/cluster_issuer/defaults/main.yml
  roles/openstack_cli/templates/atmosphere.sh.j2
  roles/openstack_cli/templates/openrc.j2
  roles/openstacksdk/templates/clouds.yaml.j2
Labels: gate

#1227 Switch to Antelope images
  images/barbican/Dockerfile
  images/cinder/Dockerfile
  images/designate/Dockerfile
  images/designate/patches/designate/0000-Fix-Mysql-default-character-setting-utf8mb4.patch
  images/glance/Dockerfile
  images/glance/patches/glance_store/0000-rbd-compute-appropriate-resize-amount-before-resizin.patch
  images/heat/Dockerfile
  images/horizon/Dockerfile
  images/horizon/patches/horizon/0000-fix-ignore-errors-when-flavors-are-deleted.patch
  images/horizon/patches/horizon/0001-Fixing-Incorrect-URL-when-browsing-Swift-containers.patch
  images/ironic/Dockerfile
  images/keystone/Dockerfile
  images/keystone/patches/keystone/0000-Ensure-application-credentials-take-account-of-impli.patch
  images/magnum/Dockerfile
  images/magnum/patches/magnum/0001-Fix-Trust-token-scope-for-drivers.patch
  images/manila/Dockerfile
  images/manila/patches/manila/0000-fix-stop-using-batch_op-for-rename_table.patch
  images/neutron/Dockerfile
  images/neutron/patches/neutron/0001-fix-ovn-set-mtu-in-external_ids-correctly.patch
  images/nova/Dockerfile
  images/octavia/Dockerfile
  images/openstack-venv-builder/Dockerfile
  images/placement/Dockerfile
  images/senlin/Dockerfile
  images/tempest/Dockerfile
  roles/defaults/vars/main.yml
  zuul.d/container-images/base.yaml
  zuul.d/playbooks/build-collection/run.yml
Labels: gate

#1246 fix: allow ssh login for nova user in nova-ssh image
  zuul.d/container-images/nova-ssh.yaml
Labels: gate

#1247 Add venafi support
  doc/source/deploy/certificates.rst
  doc/source/deploy/index.rst
  roles/cluster_issuer/README.md
  roles/cluster_issuer/defaults/main.yml
  roles/cluster_issuer/tasks/type/venafi/main.yml
  roles/defaults/vars/main.yml
  roles/ingress/defaults/main.yml
  roles/ingress/templates/ingress.yml.j2
  roles/openstack_helm_ingress/README.md
Labels: gate

#1258 Bump MCAPI to 0.18.0
  images/magnum/Dockerfile
Labels: gate, magnum

#1255 Mount CA into Keystone + Magnum
  playbooks/infrastructure.yml
  roles/cluster_issuer/tasks/main.yml
  roles/cluster_issuer/tasks/type/acme/solver/cloudflare.yml
  roles/cluster_issuer/tasks/type/acme/solver/http01.yml
  roles/cluster_issuer/tasks/type/acme/solver/rfc2136.yml
  roles/cluster_issuer/tasks/type/acme/solver/route53.yml
  roles/cluster_issuer/tasks/type/ca/main.yml
  roles/cluster_issuer/tasks/type/self-signed/main.yml
  roles/cluster_issuer/tasks/type/venafi/main.yml
  roles/defaults/defaults/main.yml
  roles/keepalived/tasks/main.yml
  roles/keycloak/tasks/main.yml
  roles/keystone/vars/main.yml
  roles/magnum/vars/main.yml
Labels: gate

#1254 Enable setting CA for Venafi
  doc/source/deploy/certificates.rst
  roles/cluster_issuer/defaults/main.yml
  roles/cluster_issuer/tasks/type/venafi/main.yml
  roles/openstack_cli/templates/atmosphere.sh.j2
  roles/openstack_cli/templates/openrc.j2
  roles/openstacksdk/templates/clouds.yaml.j2
Labels: gate

#1268 Add missing buildset registry dependency
  zuul.d/container-images/cluster-api-provider-openstack.yaml
  zuul.d/container-images/kubernetes-entrypoint.yaml
  zuul.d/container-images/openvswitch.yaml
  zuul.d/container-images/python-openstackclient.yaml
  zuul.d/container-images/ubuntu.yaml
Labels: gate

#1265 Bump OVS for DPDK issues
  images/openvswitch/Dockerfile
Labels: gate

#1264 Build requirements from pinned Git hash
  images/openstack-venv-builder/Dockerfile
Labels: gate
