Repository vexxhost/atmosphere, pull requests merged in 2025-09, with the labels that each got.

#2902 feat: enable confluent-kafka
  images/openstack-venv-builder/Dockerfile
  mise.toml
  releasenotes/notes/add-confluent-kafka-05af475d15ef0b6a.yaml
Labels: backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2928 chore: drop local patch for networking-generic-switch
  docker-bake.hcl
  images/neutron/Dockerfile
  patches/openstack/networking-generic-switch/0001-cast-numeric-netmiko-kwargs-to-native-types.patch
Labels: skip-release-notes

#2927 chore: drop local patch for networking-generic-switch
  docker-bake.hcl
  images/neutron/Dockerfile
  patches/openstack/networking-generic-switch/0001-cast-numeric-netmiko-kwargs-to-native-types.patch
Labels: skip-release-notes

#2935 chore: use github.com for git clones
  build/build-manila-image.sh
  docker-bake.hcl
  images/barbican/Dockerfile
  images/cinder/Dockerfile
  images/designate/Dockerfile
  images/glance/Dockerfile
  images/heat/Dockerfile
  images/horizon/Dockerfile
  images/ironic/Dockerfile
  images/keystone/Dockerfile
  images/magnum/Dockerfile
  images/manila/Dockerfile
  images/neutron/Dockerfile
  images/nova/Dockerfile
  images/octavia/Dockerfile
  images/openstack-venv-builder/Dockerfile
  images/ovn-bgp-agent/Dockerfile
  images/placement/Dockerfile
  images/tempest/Dockerfile
  renovate.json
Labels: skip-release-notes

#2936 chore: use github.com for git clones
  build/build-manila-image.sh
  docker-bake.hcl
  images/barbican/Dockerfile
  images/cinder/Dockerfile
  images/designate/Dockerfile
  images/glance/Dockerfile
  images/heat/Dockerfile
  images/horizon/Dockerfile
  images/ironic/Dockerfile
  images/keystone/Dockerfile
  images/magnum/Dockerfile
  images/manila/Dockerfile
  images/neutron/Dockerfile
  images/nova/Dockerfile
  images/octavia/Dockerfile
  images/openstack-venv-builder/Dockerfile
  images/ovn-bgp-agent/Dockerfile
  images/placement/Dockerfile
  images/tempest/Dockerfile
  renovate.json
Labels: skip-release-notes

#2930 chore: update neutron + drop patches
  docker-bake.hcl
  patches/openstack/neutron/0002-Fix-ovn-db-sync-with-log-resources.patch
  patches/openstack/neutron/0002-fix-ha-chassis-group.patch
Labels: skip-release-notes

#2931 chore: update neutron + drop patches
  docker-bake.hcl
  patches/openstack/neutron/0002-Fix-ovn-db-sync-with-log-resources.patch
  patches/openstack/neutron/0002-fix-ha-chassis-group.patch
Labels: skip-release-notes

#2962 chore: add pymemcache to replace python-memcached
  images/openstack-venv-builder/Dockerfile
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2970 Fix cinder staffeln conf reference
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/fix-staffeln-policy-flag-f890d2115be282bf.yaml
  roles/cinder/tasks/main.yml
Labels: backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#3000 enable neutron taas service plugin for port mirroring
  releasenotes/notes/enable-neutron-ovn-taas-756413784b47385c.yaml
  roles/neutron/vars/main.yml
Labels: backport stable/2025.1

#3035 [stable/2025.1]fix: update neutron chart to fix openvswitch config missing
  charts/neutron/templates/bin/_neutron-server.sh.tpl
  charts/patches/neutron/0008-Neutron-ovn-adopt-uwsgi.patch
Labels: skip-release-notes

#3041 [stable/zed]Fix senlin upgrade zed
  roles/senlin/vars/main.yml
Labels: skip-release-notes

#3045 Bump neutron-policy-server
  .github/styles/config/vocabularies/Base/accept.txt
  images/neutron/Dockerfile
  releasenotes/notes/neutron-policy-server-network-scope-32cc55500d68fac9.yaml
Labels: backport stable/2024.1, backport stable/2024.2, backport stable/2025.1
