Repository vexxhost/atmosphere, pull requests merged in 2025-08, with the labels that each got.

#2841 [cinder] sync image patch with RBD
  images/cinder/patches/cinder/0002-Directly-import-converted-image-to-RBD.patch
Labels: skip-release-notes, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2870 fix(designate): set producer replicas to 1
  releasenotes/notes/tune-down-producer-a12e366b19f5b839.yaml
  roles/designate/vars/main.yml
Labels: backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2880 set libvirt remote API TLS version to 1.3
  releasenotes/notes/set-libvirt-remote-api-tls-version-240a4fbb87c1f07e.yaml
  roles/libvirt/vars/main.yml
Labels: backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2881 enforce node exporter to use tls 1.3
  roles/kube_prometheus_stack/defaults/main.yml
  roles/kube_prometheus_stack/releasenotes/notes/set-node-exporter-tls-version-0102972e7630170e.yaml
Labels: backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1
