Repository vexxhost/atmosphere, pull requests merged in 2025-05, with the labels that each got.

#2558 [stable/2024.1] Drop max_allowed_packet config
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml
  roles/percona_xtradb_cluster/vars/main.yml
  roles/percona_xtradb_cluster/vars_test.go
Labels: gate

#2559 [stable/2023.2] Drop max_allowed_packet config
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml
  roles/percona_xtradb_cluster/vars/main.yml
  roles/percona_xtradb_cluster/vars_test.go
Labels: gate

#2561 [stable/zed] Drop max_allowed_packet config
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml
  roles/percona_xtradb_cluster/vars/main.yml
  roles/percona_xtradb_cluster/vars_test.go
Labels: gate

#2579 ci: switch gotest to gha
  .github/workflows/ci.yaml
  cmd/pinimages/pinimages.go
  cmd/pinimages/pinimages_test.go
  roles/defaults/vars.go
  zuul.d/jobs.yaml
  zuul.d/project.yaml
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2569 fix(ovs): Remove stale PID file at OVS startup
  charts/openvswitch/templates/bin/_openvswitch-vswitchd.sh.tpl
  charts/patches/openvswitch/0002-clean-ovs-pid.patch
  charts/patches/openvswitch/releasenotes/notes/fix-stale-ovs-pid-file-d8eee12d13ad0ffe.yaml
Labels: gate, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2590 ci: switch rust to gha
  .github/workflows/ci.yaml
  Cargo.lock
  crates/kube-prometheus-stack/Cargo.toml
  crates/kube-prometheus-stack/src/lib.rs
  crates/rustainers/src/lib.rs
  flake.lock
  flake.nix
  hack/promtool-test.py
  tox.ini
  zuul.d/jobs.yaml
  zuul.d/playbooks/cargo-test/run.yml
  zuul.d/playbooks/promtool/pre.yml
  zuul.d/project.yaml
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2591 [Backport stable/2024.2] ci: switch rust to gha
  .github/workflows/ci.yaml
  Cargo.lock
  crates/kube-prometheus-stack/Cargo.toml
  crates/kube-prometheus-stack/src/lib.rs
  crates/rustainers/src/lib.rs
  flake.lock
  flake.nix
  hack/promtool-test.py
  tox.ini
  zuul.d/jobs.yaml
  zuul.d/playbooks/cargo-test/run.yml
  zuul.d/playbooks/promtool/pre.yml
  zuul.d/project.yaml
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1

#2557 [stable/2024.2] Drop max_allowed_packet config
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml
  roles/percona_xtradb_cluster/vars/main.yml
  roles/percona_xtradb_cluster/vars_test.go
Labels: gate

#2592 ci: switch linters to gha
  .github/styles/Microsoft/SentenceLength.yml
  .github/styles/config/vocabularies/Base/accept.txt
  .github/workflows/ci.yaml
  .github/workflows/linters.yaml
  .pre-commit-config.yaml
  flake.nix
  tox.ini
  zuul.d/jobs.yaml
  zuul.d/playbooks/common/generate-changelog.yml
  zuul.d/playbooks/linters/pre.yml
  zuul.d/project.yaml
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2605 ci: skip ci on gomod changes
  zuul.d/jobs.yaml
Labels: backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2537 fix libvirt tls sidecar missing libvirt run directory
  .github/styles/config/vocabularies/Base/accept.txt
  charts/libvirt/templates/daemonset-libvirt.yaml
  charts/patches/libvirt/0004-libivrt-run-path.patch
  releasenotes/notes/fix-qemu-tls-renew-16e30a87662190ba.yaml
Labels: gate, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2653 feat: enable auth token cache in rook
  .github/styles/config/vocabularies/Base/accept.txt
  molecule/aio/prepare.yml
  playbooks/csi.yml
  playbooks/openstack.yml
  releasenotes/notes/enable-auth-token-cache-in-rook-9e15863e87fbe4ba.yaml
  roles/defaults/vars/main.yml
  roles/rook_ceph_cluster/vars/main.yml
Labels: backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2693 [Backport stable/2023.1] ✨ feat: add support for switching OpenStackCluster filter to ID transition
  .github/styles/config/vocabularies/Base/accept.txt
  .pre-commit-config.yaml
  docker-bake.hcl
  images/cluster-api-provider-openstack/Dockerfile
  images/source-patch/Dockerfile
  patches/kubernetes-sigs/cluster-api-provider-openstack/allow-switching-filter-name-to-id.patch
  releasenotes/notes/fix-capi-filter-name-to-id-b0039109a1056c06.yaml
  roles/defaults/vars/main.yml
Labels: gate
