Repository vexxhost/atmosphere, pull requests merged in 2025-06, with the labels that each got.

#2694 [Backport stable/zed] ✨ feat: add support for switching OpenStackCluster filter to ID transition
  .github/styles/config/vocabularies/Base/accept.txt
  .pre-commit-config.yaml
  docker-bake.hcl
  images/cluster-api-provider-openstack/Dockerfile
  images/source-patch/Dockerfile
  patches/kubernetes-sigs/cluster-api-provider-openstack/allow-switching-filter-name-to-id.patch
  releasenotes/notes/fix-capi-filter-name-to-id-b0039109a1056c06.yaml
  roles/defaults/vars/main.yml
Labels: gate

#2714 🔧 fix: update Dockerfiles to use 2023.2-eol branch for dependencies
  images/barbican/Dockerfile
  images/cinder/Dockerfile
  images/designate/Dockerfile
  images/glance/Dockerfile
  images/heat/Dockerfile
  images/horizon/Dockerfile
  images/horizon/patches/magnum-ui/0001-fix-disable-resizing-for-admins.patch
  images/horizon/patches/magnum-ui/0002-capi-Avoid-going-through-Heat-for-worker-list.patch
  images/ironic/Dockerfile
  images/keystone/Dockerfile
  images/magnum/Dockerfile
  images/manila/Dockerfile
  images/neutron/Dockerfile
  images/nova/Dockerfile
  images/octavia/Dockerfile
  images/openstack-venv-builder/Dockerfile
  images/placement/Dockerfile
Labels: skip-release-notes

#2735 [stable/2024.1]add missing cinder.auth_type
  releasenotes/notes/Fix-cinder-auth-type-9ea017879a578f2a.yaml
  roles/nova/vars/main.yml
Labels: backport stable/zed, backport stable/2023.1, backport stable/2023.2

#2746 fix: Add ha chassis group patch
  .github/styles/config/vocabularies/Base/accept.txt
  images/neutron/patches/neutron/0002-fix-ha-chassis-group.patch
  releasenotes/notes/fix-ha-chassis-group-554fdg9u8jmdfvb.yaml
Labels: backport stable/2024.2, backport stable/2025.1

#2702 ✨ chore: add neutron targets and update Dockerfiles for new structure
  docker-bake.hcl
  images/neutron/Dockerfile
  images/source-patch/Dockerfile
  patches/openstack/neutron/0001-fix-ovn-set-mtu-in-external_ids-correctly.patch
  renovate.json
Labels: skip-release-notes

#2766 feat: bump cert-manager version
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/bump-cert-manager-version-e4216ca32d5e6f53.yaml
  roles/defaults/vars/main.yml
Labels: backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2788 [Backport stable/zed] ci: update CSI job to use ubuntu-latest (#2783)
  .github/actions/molecule/action.yaml
  .github/workflows/ci.yaml
  .python-version
  galaxy.yml
  molecule/aio/group_vars/all/molecule.yml
  molecule/aio/prepare.yml
  molecule/csi/converge.yml
  playbooks/ceph.yml
  playbooks/generate_workspace.yml
Labels: skip-release-notes

#2790 [Backport stable/2023.1] ci: update CSI job to use ubuntu-latest (#2783)
  .github/actions/molecule/action.yaml
  .github/workflows/ci.yaml
  .python-version
  galaxy.yml
  molecule/aio/group_vars/all/molecule.yml
  molecule/aio/prepare.yml
  molecule/csi/converge.yml
  playbooks/ceph.yml
  playbooks/generate_workspace.yml
Labels: skip-release-notes
