Repository vexxhost/atmosphere, pull requests merged in 2025-04, with the labels that each got.

#2395 ci: switch checkcommit to github
  .github/workflows/pr.yaml
  zuul.d/jobs.yaml
  zuul.d/playbooks/check-commit/run.yml
  zuul.d/project.yaml
Labels: skip-release-notes

#2402 Add backports via labels
  .github/workflows/backports.yaml
  doc/source/developer.rst
  doc/source/index.rst
  releasenotes/notes/fix-nova-resize-issue-c5a16a80056a2420.yaml
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2

#2423 Switch to native Renovatebot
  .github/renovate.json
  zuul.d/project.yaml
Labels: backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2

#2391 support scrape percona haproxy metrics
  roles/kube_prometheus_stack/files/dashboards/haproxy.json
  roles/kube_prometheus_stack/tasks/main.yml
  roles/kube_prometheus_stack/vars/main.yml
  roles/percona_xtradb_cluster/tasks/main.yml
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2

#2449 Add Vale for releaese notes and docs
  .github/styles/Microsoft/AMPM.yml
  .github/styles/Microsoft/Accessibility.yml
  .github/styles/Microsoft/Acronyms.yml
  .github/styles/Microsoft/Adverbs.yml
  .github/styles/Microsoft/Auto.yml
  .github/styles/Microsoft/Avoid.yml
  .github/styles/Microsoft/Contractions.yml
  .github/styles/Microsoft/Dashes.yml
  .github/styles/Microsoft/DateFormat.yml
  .github/styles/Microsoft/DateNumbers.yml
  .github/styles/Microsoft/DateOrder.yml
  .github/styles/Microsoft/Ellipses.yml
  .github/styles/Microsoft/FirstPerson.yml
  .github/styles/Microsoft/Foreign.yml
  .github/styles/Microsoft/Gender.yml
  .github/styles/Microsoft/GenderBias.yml
  .github/styles/Microsoft/GeneralURL.yml
  .github/styles/Microsoft/HeadingAcronyms.yml
  .github/styles/Microsoft/HeadingColons.yml
  .github/styles/Microsoft/HeadingPunctuation.yml
  .github/styles/Microsoft/Headings.yml
  .github/styles/Microsoft/Hyphens.yml
  .github/styles/Microsoft/Negative.yml
  .github/styles/Microsoft/Ordinal.yml
  .github/styles/Microsoft/OxfordComma.yml
  .github/styles/Microsoft/Passive.yml
  .github/styles/Microsoft/Percentages.yml
  .github/styles/Microsoft/Plurals.yml
  .github/styles/Microsoft/Quotes.yml
  .github/styles/Microsoft/RangeTime.yml
  .github/styles/Microsoft/Semicolon.yml
  .github/styles/Microsoft/SentenceLength.yml
  .github/styles/Microsoft/Spacing.yml
  .github/styles/Microsoft/Suspended.yml
  .github/styles/Microsoft/Terms.yml
  .github/styles/Microsoft/URLFormat.yml
  .github/styles/Microsoft/Units.yml
  .github/styles/Microsoft/Vocab.yml
  .github/styles/Microsoft/We.yml
  .github/styles/Microsoft/Wordiness.yml
  .github/styles/Microsoft/meta.json
  .github/workflows/linters.yaml
  .vale.ini
  flake.nix
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2

#2460 fix lintner job to exclude github actions directory
  .pre-commit-config.yaml
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2

#2465 fix lintner job to exclude github actions directory
  .pre-commit-config.yaml
Labels: skip-release-notes

#2464 fix lintner job to exclude github actions directory
  .pre-commit-config.yaml
Labels: skip-release-notes

#2467 fix helm repo in CI job
  zuul.d/jobs.yaml
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2

#2468 doc: add patch fix docs
  .github/styles/config/vocabularies/Base/accept.txt
  .vale.ini
  doc/source/developer.rst
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2

#2458 [ATMOSPHERE-544] Add Octavia Amphere v2 support
  .charts.yml
  .github/styles/config/vocabularies/Base/accept.txt
  .vale.ini
  charts/octavia/templates/bin/_db-sync.sh.tpl
  charts/octavia/templates/configmap-etc.yaml
  charts/octavia/templates/job-db-drop.yaml
  charts/octavia/templates/job-db-init.yaml
  charts/octavia/templates/secret-db-persistence.yaml
  charts/octavia/values.yaml
  images/octavia/Dockerfile
  images/octavia/patches/octavia/0001-jobboard-Support-authentication-and-SSL-for-Redis-Se.patch
  releasenotes/notes/add-amphere-v2-df19890ea67e2486.yaml
  releasenotes/notes/backport-octavia-redis-fixes-551c9f3f145e3de6.yaml
  roles/octavia/defaults/main.yml
  roles/octavia/vars/main.yml
  roles/openstack_helm_endpoints/vars/main.yml
Labels: gate, backport stable/zed, backport stable/2023.1, backport stable/2023.2

#2474 chore(deps): update openstack (main) and Update ovn-bgp-agent patches
  images/barbican/Dockerfile
  images/cinder/Dockerfile
  images/designate/Dockerfile
  images/glance/Dockerfile
  images/heat/Dockerfile
  images/horizon/Dockerfile
  images/ironic/Dockerfile
  images/keystone/Dockerfile
  images/magnum/Dockerfile
  images/manila/Dockerfile
  images/neutron/Dockerfile
  images/nova/Dockerfile
  images/octavia/Dockerfile
  images/openstack-venv-builder/Dockerfile
  images/ovn-bgp-agent/Dockerfile
  images/ovn-bgp-agent/patches/ovn-bgp-agent/0001-Implement-driver-concept-for-BGP-agent.patch
  images/ovn-bgp-agent/patches/ovn-bgp-agent/0002-Add-the-support-of-create-kubernetes-resource.patch
  images/placement/Dockerfile
Labels: gate, skip-release-notes

#2496 [stable/2023.2]Backport redis multiple sentinel support
  images/octavia/patches/octavia/0002-redis-Support-multiple-sentinel-servers.patch
  releasenotes/notes/backport-octavia-redis-fixes-551c9f3f145e3de6.yaml
Labels: gate, skip-release-notes

#2515 Fix release workflow name
  .github/workflows/release.yaml
Labels: skip-release-notes, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2524 Check transaction before begin
  .charts.yml
  .github/styles/config/vocabularies/Base/accept.txt
  charts/barbican/templates/bin/_simple_crypto_kek_rewrap.py.tpl
  releasenotes/notes/improve-barbican-kek-db-session-92ae79da699adc6d.yaml
Labels: gate, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2535 [2024.2][barbican]Check transaction and fix kek rewrap
  .charts.yml
  .github/styles/config/vocabularies/Base/accept.txt
  .vale.ini
  charts/barbican/templates/bin/_db-sync.sh.tpl
  charts/barbican/templates/bin/_simple_crypto_kek_rewrap.py.tpl
  charts/barbican/templates/configmap-etc.yaml
  charts/barbican/templates/job-db-sync.yaml
  charts/barbican/values.yaml
  releasenotes/notes/barbican-allow-multiple-kek-c5ac6f192dff6ac7.yaml
  releasenotes/notes/improve-barbican-kek-db-session-92ae79da699adc6d.yaml
Labels: gate

#2546 Bump max_allowed_packet to 64M
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml
  roles/percona_xtradb_cluster/vars/main.yml
  roles/percona_xtradb_cluster/vars_test.go
Labels: gate, backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#2549 [stable/2024.1]Fix manila multiattach
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/fix-manila-multiattach-f86725dc81792a28.yaml
  roles/manila/vars/main.yml
Labels: gate

#2552 [stable/zed]Fix manila multiattach
  .github/styles/config/vocabularies/Base/accept.txt
  .vale.ini
  releasenotes/notes/fix-manila-multiattach-f86725dc81792a28.yaml
  roles/manila/vars/main.yml
Labels: gate

#2548 [stable/2024.2]Fix manila multiattach
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/fix-manila-multiattach-f86725dc81792a28.yaml
  roles/manila/vars/main.yml
Labels: gate
