Repository vexxhost/atmosphere, pull requests merged in 2025-10, with the labels that each got.

#3051 fix: ca bundle path for EL family
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/fix-ca-bundle-path-d33352911b65e755.yaml
  roles/defaults/defaults/main.yml
  roles/openstack_cli/templates/atmosphere.sh.j2
Labels: backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1

#3064 Fix Octavia LB cert renew
  .github/styles/config/vocabularies/Base/accept.txt
  releasenotes/notes/octavia-valkey-cert-fix-abf25ad08313e162.yaml
  roles/octavia/vars/main.yml
Labels: backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1, backport stable/2025.2

#3063 fix: configure nodeExporterSelector properly
  releasenotes/notes/fix-node-exporter-selector-b4b719e11b5d4e59.yaml
  roles/kube_prometheus_stack/files/jsonnet/legacy.libsonnet
  roles/kube_prometheus_stack/files/jsonnet/mixins.libsonnet
  roles/kube_prometheus_stack/files/jsonnet/tests.yml
Labels: backport stable/zed, backport stable/2023.1, backport stable/2023.2, backport stable/2024.1, backport stable/2024.2, backport stable/2025.1, backport stable/2025.2
